// Environment configuration generated by GitHub Actions
(function(window) {
    window.ENV = {
        EMAILJS_SERVICE_ID: "service_o5jyuif",
        EMAILJS_TEMPLATE_ID: "template_rer0jo8",
        EMAILJS_USER_ID: "oi1LRLkeOCZezCLSp",
        RESUME_LINK: "https://praveenganapathy.github.io/online-resume/PraveenGanapathyRavi_Resume.pdf"
    };
})(this);
